# Generated by Django 5.1.7 on 2025-03-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialUniversity',
            fields=[
                ('id_official_uni', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email_domain', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
