# Generated by Django 5.1.7 on 2025-03-25 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_officialuniversity'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id_university', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('id_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='api.account')),
            ],
        ),
    ]
