# Generated by Django 5.1.7 on 2025-03-25 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='api.account')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.university')),
            ],
        ),
    ]
